

class ExistExeption(Exception):
   pass

class NotFoundExeption(Exception):
   pass